### ISSUE TITLE
blind/invalid reads

### ISSUE THREAD

**Issue by ibtaylor** [facontidavide/ros_type_introspection#10] opened 2017-09-13 18:09 UTC
ReadFromBuffer does not know the size of `buffer_ptr`
https://github.com/facontidavide/ros_type_introspection/blob/81fd04147547e7c3ea74ff18738475dea243588e/src/deserializer.cpp#L53
https://github.com/facontidavide/ros_type_introspection/blob/81fd04147547e7c3ea74ff18738475dea243588e/src/deserializer.cpp#L64
https://github.com/facontidavide/ros_type_introspection/blob/81fd04147547e7c3ea74ff18738475dea243588e/src/parser.cpp#L116-L210
and so can have an invalid read here
https://github.com/facontidavide/ros_type_introspection/blob/4782d464852b7cebfc24bc5b8e7992b52717f094/include/ros_type_introspection/parser.hpp#L127

If the `string_size` is larger than the remaining contents of `buffer_ptr`, this should be an error. It is not safe to trust the user supplied data.
https://github.com/facontidavide/ros_type_introspection/blob/81fd04147547e7c3ea74ff18738475dea243588e/src/deserializer.cpp#L64-L65

**Comment by facontidavide** [comment] 2017-09-13 18:40
I know that this is quite fragile in THEORY, and I have in mind a way to improve it. But if the message is not corrupted, it should always work.

I am curious: have you find a practical situation in which there is a segmentation fault or memory corruption? Can I reproduce it?

**Comment by facontidavide** [comment] 2017-09-13 19:45
Take a look to this branch. It should provide a safer alternative

https://github.com/facontidavide/ros_type_introspection/tree/check_buffer_overrun

**Comment by ibtaylor** [comment] 2017-09-15 15:28
Just thought I should point it out. It assumes all the data is well formed. This isn't really acceptable if you want to process data from a potentially malicious source (yeah, I know, but I get bags from other people, so..). To actually trigger this, you would have to probably create a malicious bag outside of the ros tool suite.

That branch looks like an improvement on robustness.

I guess I think it might be bad to switch from a pointer to a vector just because now it forces the user to copy their data into a `std::vector` (since there is no way to wrap an existing buffer using `std::vector` afaik). What about having them supply `void*`/`uint8_t*` and a `size_t`/`ptrdiff_t` for the size in bytes of the memory location?

**Comment by facontidavide** [comment] 2017-09-15 15:42
Make sense, even if I believe that std ::vector is still a better design. I might also use a template to allow the user to pass std ::vector, std::array or vector_view

**Comment by facontidavide** [comment] 2017-09-15 17:02
I found a solution that will make both of us happy.
https://github.com/facontidavide/ros_type_introspection/commit/1159a1a03d5ffd95d9f39dde7c88e2448abd4062
Now you can pass a buffer as:

- raw (uint8_t* / size_t) pair for C style arrays
- std::vector
- std::array
- std::deque

Or any container that implements

-> value_type
-> operator[index]
-> size()
-> data()

**Comment by facontidavide** [comment] 2017-09-15 17:12
changed my mind. std::deque would fail because memory is NOT contiguous

https://github.com/facontidavide/ros_type_introspection/commit/3c5c4c98d2c2155df4e0a7ad4de57ae8f78f0b09

**Comment by facontidavide** [comment] 2017-09-16 15:25
I am temporary closing this issue, since this and other changes will be introduced soon in version 1.0 (currently Pull Request 11).

Once it is merged, all the API braking changes will be introduced at once. I also wrote a new funtion to Extract only part of a message, for example std_msgd::header ;)

https://github.com/facontidavide/ros_type_introspection/blob/check_buffer_overrun/include/ros_type_introspection/deserializer.hpp#L275

**Closed by facontidavide** 2017-09-16 15:25 UTC
